version: '3'

services:
  crudapi:
    container_name: crudapi
    image: francesco/crudapi:1.0.0
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - db-test
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5452:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  db-test:
    container_name: db-test
    image: postgres:12
    ports:
      - "5472:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}
